1. **¿Cómo identifica INDEC a las personas pobres?**

Para identificar a las personas pobres INDEC utiliza la metodología de la línea de pobreza o indigencia, comparando el ingreso total familiar de cada hogar con un conjunto de bienes y servicios. Define una canasta básica alimentaria, compuesta únicamente por alimentos capaces de satisfacer un umbral mínimo de necesidades energéticas y proteicas. Los hogares cuyos ingresos no logren alcanzar esa canasta mediante sus ingresos son considerados indigentes. La línea de pobreza se constituye con la canasta básica total (CBT), que eincluye otros bienes y servicios no alimentarios (vestimenta, transprte, educación, salud, etc.) Para obtener la CBT se utiliza el coeficiente de Engel, definido como la relación entre los gastos alimentarios y los gastos totales observados en la población de referencia. Y dado que las necesidades nutricionales difieren entre la población, se construye una unidad de referencia, "el adulto equivalente", para establecer luego las relaciones en las necesidades energéticas según edad y sexo de las personas. A partir de estas equivalencias se construyen las líneas de pobreza de cada hogar según su tamaño y composición. La caracterización entre pobres y no pobres se extiene a cada una de las personas que integran el hogar.

In [1]:
# Importamos OS para manipular rutas
import os

#Veo si la ruta es correcta
print(os.getcwd())

#Cambio a la ruta del curso
os.chdir("C:/Users/admin/Documents/Códigos Pytohn/UNIDAD 1")

#Chequeo que se haya cambiado.
print(os.getcwd())

C:\Users\admin
C:\Users\admin\Documents\Códigos Pytohn\UNIDAD 1

In [84]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [54]:
#Abrimos la EPH de individuos 2025

eph_individual_25= pd.read_excel("EPH_usu_1_Trim_2025_xls/EPH_usu_1er_Trim_2025_xlsx/usu_individual_T125.xlsx")

In [134]:
#Filtro por región las bases de 2025

eph_individual_patagonia_25 = eph_individual[eph_individual['REGION'] == 44]

In [138]:
#Abrimos la EPH de individuos 2005

eph_individual_05= pd.read_stata("t105_dta/Individual_t105.dta")

In [120]:
#Filtramos la región

eph_individual_patagonia_05 = eph_individual_05[eph_individual_05["region"]== "Patagónica"]

In [136]:
#Nos quedamos con variables de interés y renombramos para facilitar tratamiento en EPH 2025

eph_individual_patagonia_25 = eph_individual_patagonia_25[["ANO4","CODUSU", "NRO_HOGAR","CH04", "CH06", "CH07", "CH08", "NIVEL_ED", "ESTADO",
    "CAT_OCUP", "CAT_INAC","ITF", "IPCF", "PP07H", "PP04B_COD", "P47T", "P21", "PP04C"]]

#Pasamos todo a minúscula para poder unir

eph_individual_patagonia_25.columns = eph_individual_patagonia_25.columns.str.lower()

In [139]:
#Nos quedamos con variables de interés y renombramos para facilitar tratamiento en EPH 2005

eph_individual_patagonia_05 = eph_individual_patagonia_05[["ano4","CODUSU", "nro_hogar","ch04", "ch06", "ch07", "ch08", "nivel_ed", "estado",
    "cat_ocup", "cat_inac","itf", "ipcf", "pp07h", "pp04b_cod", "p47t", "p21", "pp04c"]]

#Pasamos todo a minúscula para poder unir

eph_individual_patagonia_05.columns = eph_individual_patagonia_05.columns.str.lower()

In [142]:
# Unir ambas bases

eph_individual_patagonia = pd.concat(
    [eph_individual_patagonia_05, eph_individual_patagonia_25],
    ignore_index=True
)

In [160]:
#Chequeamos

eph_individual_patagonia.sample(10)

,ano4,codusu,nro_hogar,ch04,ch06,ch07,ch08,nivel_ed,estado,cat_ocup,cat_inac,itf,ipcf,pp07h,pp04b_cod,p47t,p21,pp04c
2107,2005.0,219915,1.0,Mujer,54.0,Casado,Obra social (incluye PAMI),Secundaria Incompleta,Ocupado,Obrero o empleado,0.0,930.0,465.00,No,9500,280.0,150.0,0.0
7221,2025.0,TQRMNOPQPHMNKNCDEIHJF00880989,1.0,1,67,2,1.0,2,3,0,1,0.0,0.00,NaN,NaN,800000.0,0.0,NaN
2430,2005.0,125438,2.0,Mujer,33.0,Casado,Obra social (incluye PAMI),Secundaria Completa,Inactivo,0.0,Ama de casa,1200.0,300.00,0.0,,0.0,0.0,0.0
5456,2025.0,TQRMNORQYHMMKNCDEOHCH00879657,1.0,1,66,5,1.0,3,3,0,1,1500000.0,1500000.00,NaN,NaN,1500000.0,0.0,NaN
7764,2025.0,TQRMNOSPXHKOKOCDEOHCH00856459,1.0,1,57,2,1.0,4,1,3,0,5932000.0,988666.67,1.0,4000.0,850000.0,850000.0,8.0
5612,2025.0,TQRMNOSTYHJMKQCDEFPCH00874548,1.0,2,49,3,1.0,4,1,3,0,0.0,0.00,1.0,3502.0,-9.0,-9.0,9.0
4286,2025.0,TQRMNOQRVHKNKSCDEHGHJ00864168,1.0,2,74,2,1.0,1,3,0,4,1260000.0,630000.00,NaN,NaN,360000.0,0.0,NaN
1355,2005.0,231100,1.0,Mujer,31.0,Casado,Obra social (incluye PAMI),Secundaria Incompleta,Inactivo,0.0,Ama de casa,720.0,720.00,0.0,,720.0,0.0,0.0
24,2005.0,130257,1.0,Mujer,17.0,Soltero,Obra social (incluye PAMI),Primaria Completa,Inactivo,0.0,Otros,3300.0,550.00,0.0,,0.0,0.0,0.0
5817,2025.0,TQRMNORPUHLOKTCDEGNFJ00853299,1.0,2,35,2,1.0,4,3,0,7,600000.0,150000.00,NaN,NaN,0.0,0.0,NaN